name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        uses: sudo apt-get update && sudo apt install libx11-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev

      - name: Install dependencies
        run: git submodule update --init --recursive --depth=1

      - name: Create build directory
        run: mkdir -p build

      - name: Configure with CMake
        run: cmake -S . -Bbuild

      - name: Build
        run: cmake --build build
