name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: git submodule init --recursive

    - name: Create build directory
      run: mkdir -p build

    - name: Configure with CMake
      run: cmake -S . -Bbuild

    - name: Build
      run: cmake --build build
